#include "city/document.h"
#include "city/runtime.h"
#include "editor/document.h"
#include "editor/scene_extension.h"
#include "editor/group_transforms.h"
#include <fstream>
#include <iostream>
#include <chrono>
#include <set>
using namespace dfv;using J=nlohmann::json;namespace fs=std::filesystem;
static void check(bool value,const char *why){if(!value)throw std::runtime_error(why);}
int main(int argc,char **argv){try{
  const bool real=argc>1;const auto output=fs::absolute("artifacts/city");fs::create_directories(output);
  const auto folder=real?fs::u8path(argv[1]):output/"fixture";fs::create_directories(folder);
  if(!real){J d=J::parse(R"({"geometry_library":[{"id":"mesh","vertices":{"count":8,"values":[[0,0,0],[1200,0,0],[1200,0,1200],[0,0,1200],[0,3200,0],[1200,3200,0],[1200,3200,1200],[0,3200,1200]]},"polygon_material_groups":{"count":2,"values":["Walls","AirCon"]},"polylist":{"count":7,"values":[[0,0,0,1,2,3],[0,0,4,7,6,5],[0,0,0,4,5,1],[0,0,1,5,6,2],[0,0,2,6,7,3],[0,0,3,7,4,0],[0,1,4,5,6]]}}],"scene":{"nodes":[{"id":"building","geometries":[{"id":"shape","url":"#mesh"}]}],"materials":[{"id":"walls","geometry":"#shape","groups":["Walls"]},{"id":"detail","geometry":"#shape","groups":["AirCon"]}]}})");std::ofstream(folder/"Building.duf")<<d.dump();std::ofstream(folder/"Material.duf")<<R"({"scene":{"materials":[]}})";}
  city::Config config;config.directory=folder;config.blocks_x=5;config.blocks_y=4;config.lots=2;config.density=1;
  if(real){config.assets={"Building5.duf","Building Tall2.duf","Building Tall1.duf"};config.blocks_x=config.blocks_y=config.lots=4;config.density=.85;}
  if(!real){J d;std::ifstream(folder/"Building.duf")>>d;d["geometry_library"][0]["default_uv_set"]="#uv";d["uv_set_library"]=J::array({{{"id","uv"},{"vertex_count",8},{"uvs",{{"count",8},{"values",{{0,0},{1,0},{1,1},{0,1},{0,0},{1,0},{1,1},{0,1}}}}}}});std::ofstream(folder/"Building.duf")<<d.dump();}
  auto files=city::discover(folder);check(files.size()==(real?10:1),"Discovery mixed presets with buildings");
  check(city::config_from_json(city::json(config))==config,"Recipe roundtrip");
  const auto start=std::chrono::steady_clock::now();auto generated=city::generate(config,"city-test",std::vector<fs::path>{folder});const auto metadata=generated.city;
  auto duplicate=city::generate(config,"city-test",std::vector<fs::path>{folder});check(generated.loaded.scene.instances.size()==duplicate.loaded.scene.instances.size(),"Seed instance count");for(size_t i=0;i<generated.loaded.scene.instances.size();++i)check(generated.loaded.scene.instances[i].transform==duplicate.loaded.scene.instances[i].transform,"Deterministic transforms");
  editor::Document doc;doc.generation=1;city::install(doc,std::move(generated));auto snapshot=editor::initial_snapshot(doc);auto scene=doc.loaded.scene;city::Runtime runtime;runtime.bind(doc.cities,scene);J counts=J::array();
  for(int level=0;level<=4;++level){snapshot.city_views[metadata->id].forced=level;ir::Delta delta;runtime.apply(scene,snapshot.city_views,&delta);const auto &stats=runtime.stats;check(stats.buildings==metadata->buildings.size(),"LOD changed city population");check(stats.cells[std::max(1,level)-1]==metadata->cells.size(),"Forced LOD not applied");counts.push_back({{"lod",level},{"instances",stats.visible_instances},{"triangles",stats.triangles},{"unique_triangles",stats.unique_triangles}});if(level==4)for(const auto &r:metadata->regions)for(auto ci:r.cells)for(const auto &l:metadata->cells[ci].instances)for(const auto &id:l)for(const auto &i:scene.instances)if(i.id==id)check(!i.visible,"HLOD overlap");}
  auto &view=snapshot.city_views[metadata->id];view={};scene.camera.transform=ir::Transform::translate({0,0,150000});runtime.apply(scene,snapshot.city_views);check(runtime.stats.cells[3]==metadata->cells.size(),"Auto far LOD");view.locked=true;scene.camera.transform=ir::Transform::translate({0,0,10});runtime.apply(scene,snapshot.city_views);check(runtime.stats.cells[3]==metadata->cells.size(),"LOD lock failed");view.locked=false;runtime.apply(scene,snapshot.city_views);check(runtime.stats.cells[0]>0,"Auto near LOD failed");view.enabled=false;runtime.apply(scene,snapshot.city_views);check(runtime.stats.visible_instances==0,"Disabled city retained visible geometry");view.enabled=true;view.forced=1;
  const auto source=metadata->material_sources[0];const auto &s=doc.loaded.scene;auto si=std::find_if(s.instances.begin(),s.instances.end(),[&](const auto &i){return i.id==source;});snapshot.material_overrides[source][s.meshes[si->mesh].material_slots[0]]["base_color"]=J::array({1.,0.,0.});editor::apply_material_overrides(scene,s,snapshot.material_overrides);runtime.apply(scene,snapshot.city_views);for(const auto &link:metadata->materials){auto a=std::find_if(scene.instances.begin(),scene.instances.end(),[&](const auto &i){return i.id==link.instance;}),b=std::find_if(scene.instances.begin(),scene.instances.end(),[&](const auto &i){return i.id==link.source;});check(a->materials==b->materials,"Shared material propagation failed");}
  const auto file=output/(real?"night-day-city.dufex":"fixture-city.dufex");editor::save_scene_extension(file,doc,snapshot);const auto restored=editor::load_scene_extension(file,{folder},2);check(restored.document->cities.size()==1&&restored.document->cities[0]->buildings.size()==metadata->buildings.size()&&restored.snapshot.city_views==snapshot.city_views&&restored.snapshot.material_overrides==snapshot.material_overrides,"DUFEX city roundtrip failed");
  editor::append_document(doc,*restored.document,"copy/");check(doc.cities.size()==2,"Append lost city metadata");city::remove(doc,"city-test");scene=doc.loaded.scene;runtime.bind(doc.cities,scene);runtime.apply(scene,{});check(doc.cities.size()==1&&doc.cities[0]->id=="copy/city-test","Removing one city removed another");doc.loaded.scene.validate();
  city::remove(doc,"copy/city-test");check(doc.loaded.scene.instances.empty()&&doc.loaded.scene.meshes.empty()&&doc.cities.empty(),"City removal leaked resources");
  auto invalid=config;invalid.distances={3000,300,30};bool rejected=false;try{city::validate(invalid);}catch(...){rejected=true;}check(rejected,"Invalid LOD ranges accepted");
  J result={{"result","PASS"},{"buildings",metadata->buildings.size()},{"blocks",metadata->cells.size()},{"regions",metadata->regions.size()},{"levels",counts},{"seconds",std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count()}};std::ofstream(output/(real?"asset-check.json":"core-check.json"))<<result.dump(2);std::cout<<result.dump(2)<<'\n';return 0;
}catch(const std::exception &e){std::cerr<<e.what()<<'\n';return 1;}}
