#include "water_fixture.h"
#include "editor/scene_extension.h"
#include "render_ir/default_options.h"
#include "daz/documents.h"
#include "editor/ground_selection.h"
#include "editor/physics_service.h"
#include "editor/mesh_diagnostics.h"
#include <iostream>
#include <chrono>
using namespace dfv;namespace fs=std::filesystem;
static void check(bool v,const char *why){if(!v)throw std::runtime_error(why);}
template<class F>static void rejects(F f){bool rejected=false;try{f();}catch(const std::exception &){rejected=true;}check(rejected,"invalid water accepted");}
static bool covers(const ir::Mesh &m,double x,double y){for(const auto &t:m.triangles){const auto a=m.positions[t.vertices[0]],b=m.positions[t.vertices[1]],c=m.positions[t.vertices[2]];const double det=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);if(std::abs(det)<1e-12)continue;double u=((x-a.x)*(c.y-a.y)-(y-a.y)*(c.x-a.x))/det,v=((b.x-a.x)*(y-a.y)-(b.y-a.y)*(x-a.x))/det;if(u>=-1e-7&&v>=-1e-7&&u+v<=1+1e-7)return true;}return false;}
static void physics_exclusion(){
  auto d=std::make_shared<editor::Document>();auto &s=d->loaded.scene;s.materials.emplace_back();s.materials[0].id="falling-material";s.meshes.push_back(water_fixture::cylinder(.2f,0,1,16));
  ir::Instance prop;prop.id="falling/mesh";prop.materials={0};prop.transform=ir::Transform::translate({0,0,2});s.instances.push_back(prop);runtime::Target target;target.id=prop.id;target.label="Falling prop";d->catalog.targets.push_back(target);d->formulas.graphs.emplace_back();
  auto water=std::make_shared<water::Water>();water->id="non-solid-water";water->config.width=water->config.length=16;water->config.wave_height=0;water::install(*d,water);check(!editor::physics_eligible(*d,1),"native water permits physics simulation");
  auto snapshot=editor::initial_snapshot(*d);for(auto &v:snapshot.values){v.physics.enabled=true;v.physics.run_sequence=1;v.physics.rounds=90;v.physics.damping=0;}
  runtime::PhysicsOptions options;options.ground=false;options.refresh_hz=60;editor::PhysicsService service;const auto serial=service.request(d,snapshot,options);const auto until=std::chrono::steady_clock::now()+std::chrono::seconds(12);bool passed=false;
  while(std::chrono::steady_clock::now()<until){service.request_frame();if(auto result=service.take()){check(result->error.empty(),result->error.c_str());if(result->serial==serial){check(result->stats.objects<=1,"native water was simulated");for(const auto &v:result->delta.instances)check(v.index!=1,"physics moved native water");if(result->stats.steps>=90&&result->scene){check(result->scene->instances[0].transform.value[11]<-2,"native water became a solid collision floor");passed=true;break;}service.acknowledge(result);}}std::this_thread::sleep_for(std::chrono::milliseconds(5));}
  check(passed,"water physics exclusion timed out");
}
int main(){try{
  const auto started=std::chrono::steady_clock::now();water::Water w;w.id="water-test";w.config.width=w.config.length=128;w.config.precision=.5;w.config.coast=true;w.config.scan_scene=false;
  const auto a=water::wave(w.config,12.34,-56.78);auto c=w.config;c.time=19.75;const auto b=water::wave(c,12.34,-56.78);check(a.z!=b.z,"time did not affect waves");check(water::wave(w.config,12.34,-56.78).z==a.z,"wave sample not deterministic");
  auto invalid=c;invalid.depth=0;rejects([&]{water::validate(invalid);});invalid=c;invalid.time=std::numeric_limits<double>::infinity();rejects([&]{water::validate(invalid);});
  water::Obstacle column{"column",water_fixture::cylinder(),{},true};w.cache=water::calculate(w,{column},123);
  check(!w.cache->cells.empty(),"missing contact cells");const auto near=water::mesh(w,{0,-15,8}),far=water::mesh(w,{2000,-2000,1000});
  check(!covers(near,0,0)&&!covers(far,0,0),"water covers interior of column");check(covers(near,7,0)&&covers(far,7,0),"water was removed outside column");
  double penetration=0;for(const auto &t:near.triangles){auto a=near.positions[t.vertices[0]],b=near.positions[t.vertices[1]],c=near.positions[t.vertices[2]];for(auto p:{a,b,c,ir::Vec3{(a.x+b.x+c.x)/3,(a.y+b.y+c.y)/3,(a.z+b.z+c.z)/3}})penetration=std::max(penetration,3.-std::hypot(p.x,p.y));}
  {auto dense=w;dense.config.density=8;dense.config.foam_uv_scale=2.5;check(water::same_shape(w.config,dense.config),"display detail invalidated coast cache");
    const auto m=water::mesh(dense,{0,-15,8}),base=water::mesh(w,{0,-15,8});check(m.positions.size()<=base.positions.size()*8&&!covers(m,0,0)&&covers(m,7,0),"density changed coast clipping or exceeded 8x");
    auto encoded=water::json(dense);check(water::from_json(encoded)->config==dense.config,"density/foam UV roundtrip failed");encoded.erase("density");encoded.erase("foam_uv_scale");auto legacy=water::from_json(encoded);check(legacy->config.density==1&&legacy->config.foam_uv_scale==1,"legacy water defaults changed");
    check(water::material(dense).water->foam_uv_scale==2.5f,"foam UV did not reach render IR");dense.config.density=8.01;rejects([&]{water::validate(dense.config);});}
  check(penetration<.12,"column contact exceeds sampling error budget");
  column.transform=ir::Transform::translate({12,0,0});w.cache=water::calculate(w,{column},124);auto moved=water::mesh(w,{0,-15,8});check(covers(moved,0,0)&&!covers(moved,12,0),"moving column left a stale hole");
  column.transform=ir::Transform::translate({12,0,-30});w.cache=water::calculate(w,{column},125);check(covers(water::mesh(w),12,0),"submerged column incorrectly removes water above it");
  column.transform=ir::Transform::translate({12,0,30});w.cache=water::calculate(w,{column},126);check(covers(water::mesh(w),12,0),"airborne column incorrectly removes water below it");
  column.mesh.triangles.pop_back();rejects([&]{water::calculate(w,{column},127);});
  {auto dense=w;dense.config.wave_height=0;dense.config.precision=.1;water::Obstacle shelf;shelf.id="flat-shelf";shelf.mesh.positions={{-64,-64,0},{64,-64,0},{64,64,0},{-64,64,0}};shelf.mesh.triangles={{{0,1,2}},{{0,2,3}}};
    const auto bounded=water::calculate(dense,{shelf},128);check(bounded->cells.size()<=50000&&bounded->sampling_spacing>dense.config.precision&&!bounded->warnings.empty(),"coast budget did not reduce detail with an explicit warning");
    dense.cache=bounded;check(water::from_json(water::json(dense))->cache->sampling_spacing==bounded->sampling_spacing,"effective coast spacing was not serialized");}
  auto encoded=water::json(w);auto restored=water::from_json(encoded);check(restored->config==w.config&&restored->cache->cells==w.cache->cells,"water JSON roundtrip failed");encoded["cache"]["cells"].push_back({0,0,27,{1,1,1,1,1}});rejects([&]{water::from_json(encoded);});
  water::Water ocean;ocean.id="ocean";auto ocean_mesh=water::mesh(ocean,{0,0,10});check(ocean_mesh.triangles.size()<400000,"large ocean has unbounded tessellation");ir::Bounds bounds;for(auto p:ocean_mesh.positions)bounds.add(p);check(bounds.extent()>59990,"large ocean lost coverage");
  const auto coarse=water::mesh(ocean,{1500,-1500,1000});check(coarse.positions.size()<ocean_mesh.positions.size(),"diagnostic regression did not exercise shrinking topology");
  for(const auto eye:{ir::Vec3{0,0,10},ir::Vec3{1500,-1500,1000},ir::Vec3{0,0,90000}}){const auto base=water::mesh(ocean,eye);auto dense=ocean;dense.config.density=8;const auto m=water::mesh(dense,eye);check(m.positions.size()>base.positions.size()&&m.positions.size()<=base.positions.size()*8,"ocean density did not increase within 8x cap");std::cout<<"density vertices "<<base.positions.size()<<" -> "<<m.positions.size()<<'\n';}
  check(!editor::vertex_displacement(ocean_mesh.positions,coarse.positions,true),"shrinking mesh accessed nonexistent diagnostic vertices");
  check(!editor::vertex_displacement(coarse.positions,ocean_mesh.positions,true),"expanding mesh was treated as vertex-corresponding");
  const std::vector<ir::Vec3> rest{{0,0,0},{1,1,1}},deformed{{0,3,4},{1,1,1}};
  check(editor::vertex_displacement(rest,deformed,true)==5,"ordinary model displacement diagnostic regressed");check(!editor::vertex_displacement(rest,deformed,false),"same-count remesh invented vertex correspondence");
  const auto folder=fs::temp_directory_path()/("dfv-water-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));fs::create_directories(folder);auto file=folder/"columns.duf";water_fixture::write(file);auto d=water_fixture::load(file);
  auto water=std::make_shared<water::Water>();water->id="native-water";water->config.width=water->config.length=128;water->config.coast=true;water->config.scan_scene=false;water->config.precision=1;
  for(const auto &o:d.loaded.objects)water->config.sources.push_back({o.id,true});water::install(d,water);auto snapshot=editor::initial_snapshot(d);snapshot.options.environment=ir::default_options(true);snapshot.options.tonemapper=ir::default_options(false);
  {auto grouped=d;grouped.loaded.nodes.push_back({"columns-group",{},"Columns",true});for(auto &o:grouped.loaded.objects)o.parent="#columns-group";
    std::vector<ir::Bounds> boxes(grouped.loaded.scene.instances.size());for(int i=0;i<3;++i){boxes[i].add({float(i*10),0,0});boxes[i].add({float(i*10+2),3,4});}
    const auto candidates=water::candidates(grouped,boxes);check(candidates.size()==4,"candidate list includes native water or misses group");for(const auto &v:candidates)check(v.volume==(v.id=="columns-group"?264.:24.),"candidate volume did not use world AABB union");
    boxes[0].add({-10,0,0});const auto moved=water::candidates(grouped,boxes);for(const auto &v:moved)if(v.id=="columns-group")check(v.volume==384.,"candidate bounds did not follow moving objects");}
  water->cache=water::recalculate(d,snapshot,*water);check(water->cache->objects==3,"scene candidates not resolved");water::install(d,water);const auto stamp=water::input_stamp(d,snapshot);check(stamp==water->cache->stamp,"cache stale immediately after rebuild");
  {auto placement=snapshot;std::vector<ir::Bounds> bounds(d.loaded.scene.instances.size());std::vector<ir::Transform> worlds(d.catalog.targets.size());const auto index=d.catalog.targets.back().instance;worlds.back()=ir::Transform::translate({0,0,3});placement.values.back().transform.translation_cm.y=300;
    bounds[index].add({-64,-64,2});bounds[index].add({64,64,4});const auto selected=editor::ground_selection(d,{water->id});check(editor::align_ground_selection(d,placement,selected,bounds,worlds,{}),"water ground alignment did not run");check(std::abs(placement.values.back().transform.translation_cm.y)<1e-5,"water aligned its trough instead of its reference plane");
    auto later=*water;later.config.time=123.4;later.config.wave_height=20;check(water::reference_bounds(later,worlds.back()).minimum.z==water::reference_bounds(*water,worlds.back()).minimum.z,"wave settings changed ground datum");}
  const auto save=folder/"water.dufex";editor::save_scene_extension(save,d,snapshot);check(daz::read_document_file(save).at("version")==2,"water downgraded DUFEX");fs::remove(file);
  auto opened=editor::load_scene_extension(save,{},44);check(opened.document->waters.size()==1&&opened.document->catalog.targets.size()==4,"native objects not restored");check(water::json(*opened.document->waters[0])==water::json(*water),"saved water/cache changed");check(water::input_stamp(*opened.document,opened.snapshot)==stamp,"cache stamp changed on reopen");
  auto changed=opened.snapshot;changed.values[0].transform.translation_cm.x+=500;check(water::input_stamp(*opened.document,changed)!=stamp,"object motion did not invalidate coast");auto new_cache=water::recalculate(*opened.document,changed,*opened.document->waters[0]);check(new_cache->stamp!=stamp,"rebuild did not consume edited transforms");
  auto geometry_edit=*opened.document;geometry_edit.loaded.scene.meshes[0].positions[0].z+=1;check(water::input_stamp(geometry_edit,opened.snapshot)!=stamp,"same-size geometry edit did not invalidate coast");
  auto opacity_edit=opened.snapshot;const auto &obstacle=opened.document->loaded.scene.instances[0];opacity_edit.material_overrides[obstacle.id][opened.document->loaded.scene.meshes[obstacle.mesh].material_slots[0]]["opacity"]=0;check(water::input_stamp(*opened.document,opacity_edit)!=stamp,"hidden material did not invalidate coast");
  auto edited=std::make_shared<water::Water>(*opened.document->waters[0]);edited->config.time=23;edited->cache.reset();auto water_snapshot=opened.snapshot;water_snapshot.water_overrides={edited};
  check(water::effective(*opened.document,water_snapshot)[0]->config.time==23&&opened.document->waters[0]->config.time!=23,"water parameter snapshot mutated shared document");
  auto replayed=opened.snapshot;editor::apply_snapshot_json(*opened.document,replayed,editor::snapshot_json(*opened.document,water_snapshot));check(water::json(*replayed.water_overrides.at(0))==water::json(*edited),"water snapshot did not roundtrip");
  editor::save_scene_extension(folder/"water-parameter-edit.dufex",*opened.document,water_snapshot);auto edit_loaded=editor::load_scene_extension(folder/"water-parameter-edit.dufex",{},47);check(edit_loaded.document->waters[0]->config.time==23&&!edit_loaded.document->waters[0]->cache,"saved water parameter edit lost on reopen");
  {auto candidates=opened.document->loaded.scene;for(size_t i=0;i<3;++i)candidates.instances[i].transform.value[11]+=100;check(water::inputs(*opened.document,candidates,*water).objects.empty(),"airborne geometry allocated coast colliders");}
  {auto candidates=opened.document->loaded.scene;for(size_t i=0;i<3;++i)candidates.instances[i].transform.value.fill(0);check(water::inputs(*opened.document,candidates,*water).objects.empty(),"zero-scale source aborted coast calculation");}
  {auto candidates=opened.document->loaded.scene;for(auto &m:candidates.materials)m.transmission=1;auto automatic=*water;automatic.config.scan_scene=true;automatic.config.sources.clear();check(water::inputs(*opened.document,candidates,automatic).objects.empty(),"automatic coast treated transmissive surfaces as terrain");check(water::inputs(*opened.document,candidates,*water).objects.size()==3,"explicit volume could not override automatic transmission filter");}
  {auto candidates=opened.document->loaded.scene;for(size_t i=0;i<3;++i)candidates.meshes[candidates.instances[i].mesh].material_slots[0]="matWater";auto automatic=*water;automatic.config.scan_scene=true;automatic.config.sources.clear();const auto excluded=water::inputs(*opened.document,candidates,automatic);check(excluded.objects.empty()&&!excluded.warnings.empty(),"opaque legacy matWater consumed the coast budget");check(water::inputs(*opened.document,candidates,*water).objects.size()==3,"manual source could not override water name inference");}
  {auto candidates=opened.document->loaded.scene;auto &m=candidates.meshes[0];m.triangles.resize(2000,m.triangles.front());m.subdivision.enabled=true;m.subdivision.level=6;auto coarse=*water;coarse.config.precision=100;const auto input=water::inputs(*opened.document,candidates,coarse);check(!input.warnings.empty()&&input.objects.front().mesh.triangles.size()==2000,"coarse shore sampling allocated render subdivision");}
  editor::Document empty;auto only=std::make_shared<water::Water>();only->id="standalone-water";only->config.width=only->config.length=32;water::install(empty,only);auto empty_snapshot=editor::initial_snapshot(empty);editor::save_scene_extension(folder/"standalone.dufex",empty,empty_snapshot);check(editor::load_scene_extension(folder/"standalone.dufex",{},45).document->waters.size()==1,"water-only scene failed");
  editor::append_document(empty,*opened.document,"copy/");check(empty.waters.size()==2&&empty.waters[1]->id=="copy/native-water","append identity was not remapped");auto appended_snapshot=editor::initial_snapshot(empty);editor::save_scene_extension(folder/"append.dufex",empty,appended_snapshot);check(editor::load_scene_extension(folder/"append.dufex",{},46).document->waters.size()==2,"appended water failed to restore");
  editor::remove_target(*opened.document,opened.snapshot,3);check(opened.document->waters.empty(),"deleted water recipe survived");
  physics_exclusion();
  std::cout<<nlohmann::json{{"result","PASS"},{"contact_cells",w.cache->cells.size()},{"near_triangles",near.triangles.size()},{"far_triangles",far.triangles.size()},{"ocean_triangles",ocean_mesh.triangles.size()},{"max_column_penetration_m",penetration},{"seconds",std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count()},{"fixture",folder.string()}}.dump(2)<<'\n';return 0;
}catch(const std::exception &e){std::cerr<<e.what()<<'\n';return 1;}}
