  bool water_test_=false;int water_test_stage_=0;std::string water_test_id_;uint64_t water_test_stamp_=0;size_t water_test_triangles_=0;
  nlohmann::json water_checks_=nlohmann::json::array();
  bool water_scene_test_=false;
  qint64 water_scene_recorded_=0;
  uint64_t water_navigation_clay_=0;
  const Document *water_test_shared_document_=nullptr;size_t water_test_scene_updates_=0;
  void water_scene_test_tick(const RenderStatus &state){
    auto fail=[&](const std::string &why){finish_test(false,why);water_test_=false;};
    if(QDateTime::currentMSecsSinceEpoch()-test_started_>600000){fail("完整场景水体验证超时");return;}
    if(!state.error.empty()||!state.edit_error.empty()||!water_error_.empty()){fail(state.error+state.edit_error+water_error_);return;}
    if(loading_||!document_||state.generation!=document_->generation||state.applied_revision!=snapshot_.revision||state.presented_revision!=snapshot_.revision||state.presented_epoch!=state.requested_epoch||state.camera.epoch!=renderer_->input_camera().epoch||state.preview||state.samples<4)return;
    auto check=[](bool value,const char *why){if(!value)throw std::runtime_error(why);};
    auto record=[&](const char *name){const auto now=QDateTime::currentMSecsSinceEpoch();PROCESS_MEMORY_COUNTERS_EX memory{};memory.cb=sizeof(memory);K32GetProcessMemoryInfo(GetCurrentProcess(),reinterpret_cast<PROCESS_MEMORY_COUNTERS *>(&memory),sizeof(memory));water_checks_.push_back({{"stage",name},{"elapsed_ms",water_scene_recorded_?now-water_scene_recorded_:0},{"private_bytes",memory.PrivateUsage},{"source",document_->source_file.string()},{"sessions",state.sessions},{"instances",state.adapter.instances},{"triangles",state.adapter.triangles},{"max_displacement",state.max_displacement},{"water_count",document_->waters.size()}});water_scene_recorded_=now;renderer_->trace(name);std::ofstream(output_/"water-checks.json")<<water_checks_.dump(2);};
    try{
      if(water_test_stage_==0){check(document_->waters.empty(),"Use a source scene without native water");record("full-scene-loaded");findChild<QAction *>("CreateWater")->trigger();}
      else if(water_test_stage_==1){check(document_->waters.size()==1&&selected_water(),"Create menu did not select native water");water_test_shared_document_=document_.get();water_test_scene_updates_=state.adapter.scene_updates;water_navigation_clay_=state.clay_presentations;record("water-created");renderer_->camera_view({4.6f,.4f,0,90000,1.015f,.595f});}
      else if(water_test_stage_==2){check(state.clay_presentations==water_navigation_clay_,"远距离相机移动触发白模等待");record("far-lod");renderer_->camera_view({4.6f,.4f,0,60,1.015f,.595f});}
      else if(water_test_stage_==3){check(state.clay_presentations==water_navigation_clay_,"近距离相机移动触发白模等待");record("near-lod");water_panel_->findChild<QDoubleSpinBox *>("time")->setValue(4.5);}
      else if(water_test_stage_==4){check(selected_water()&&water::effective(*document_,snapshot_).front()->config.time==4.5,"Water time did not update");check(document_.get()==water_test_shared_document_&&state.adapter.scene_updates==water_test_scene_updates_,"Water time/LOD copied or synchronized the entire scene");record("time-edit");auto config=selected_water()->config;config.coast=true;generate_water(config,selected_water()->id,true);}
      else if(water_test_stage_==5){const auto *w=selected_water();check(w&&w->cache&&w->cache->objects>0&&!w->cache->cells.empty(),"Full-scene coast did not produce contacts");check(w->cache->stamp==water::input_stamp(*document_,snapshot_),"Full-scene coast stamp stale");check(document_.get()==water_test_shared_document_&&state.adapter.scene_updates==water_test_scene_updates_,"Coast rebuild copied or synchronized the entire scene");std::ofstream(output_/"coast.json")<<water::json(*w).dump();record("full-scene-coast");delete_selection();}
      else if(water_test_stage_==6){check(document_->waters.empty(),"Delete left native water behind");record("deleted");history_->undo();}
      else if(water_test_stage_==7){check(document_->waters.size()==1,"Undo failed to restore native water");record("undo");screen()->grabWindow(winId()).save(QString::fromStdWString((output_/"full-scene-water.png").wstring()));
        for(const auto &i:document_->loaded.scene.instances)for(const auto &slot:document_->loaded.scene.meshes[i.mesh].material_slots)if(slot=="matWater")snapshot_.material_overrides[i.id][slot]["opacity"]=0;send();
      }
      else if(water_test_stage_==8){record("legacy-surface-hidden");for(size_t t=0;t<document_->catalog.targets.size();++t)if(water::find(document_->waters,document_->catalog.targets[t].id)){choose(int(t));break;}const auto *w=selected_water();check(w,"Water selection lost after undo");generate_water(w->config,w->id,true);}
      else if(water_test_stage_==9){check(selected_water()->cache->stamp==water::input_stamp(*document_,snapshot_),"Hidden legacy surface cache was not rebuilt");record("native-coast-visible");screen()->grabWindow(winId()).save(QString::fromStdWString((output_/"full-scene-native-water.png").wstring()));finish_test(true);water_test_=false;return;}
      ++water_test_stage_;
    }catch(const std::exception &e){fail(e.what());}
  }
  void water_test_tick(const RenderStatus &state){
    if(water_scene_test_){water_scene_test_tick(state);return;}
    if(QDateTime::currentMSecsSinceEpoch()-test_started_>240000){finish_test(false,"水体界面验证超时");water_test_=false;return;}
    if(!state.error.empty()||!state.edit_error.empty()){finish_test(false,state.error+state.edit_error);water_test_=false;return;}
    if(loading_||!document_)return;auto check=[](bool v,const char *why){if(!v)throw std::runtime_error(why);};
    try{
      if(water_test_stage_==0){
        for(const char *name:{"CreateEnvironment","CreateTonemapper"}){auto *action=findChild<QAction *>(name);check(action,"Missing creation menu action");action->trigger();const auto before=ir::options_json(snapshot_.options);action->trigger();check(before==ir::options_json(snapshot_.options),"Create action overwrote existing settings");}
        check(findChild<QToolButton *>("MorphCollapse")->text()==QStringLiteral("参数"),"Parameter group not renamed");
        for(auto *action:findChildren<QAction *>())check(action->text()!=QStringLiteral("保存环境与色调设置…")&&action->text()!=QStringLiteral("载入环境与色调设置…"),"Old settings actions still present");
        findChild<QAction *>("CreateWater")->trigger();++water_test_stage_;return;
      }
      if(state.generation!=document_->generation||state.applied_revision!=snapshot_.revision||state.presented_revision!=snapshot_.revision||state.presented_epoch!=state.requested_epoch||state.preview||state.samples<4)return;
      auto record=[&](const char *name){water_checks_.push_back({{"stage",name},{"sessions",state.sessions},{"triangles",state.adapter.triangles},{"morph_evaluations",state.evaluation.morph_evaluations},{"water_count",document_->waters.size()}});std::ofstream(output_/"water-checks.json")<<water_checks_.dump(2);};
      auto choose_water=[&]{for(size_t t=0;t<document_->catalog.targets.size();++t)if(document_->catalog.targets[t].id==water_test_id_+"/surface"){choose(int(t));return;}throw std::runtime_error("Water target missing");};
      if(water_test_stage_==1){check(document_->waters.size()==1&&water_panel_->isVisible(),"Water creation/selection failed");water_test_id_=document_->waters[0]->id;auto config=document_->waters[0]->config;config.width=config.length=128;config.coast=true;config.scan_scene=false;config.precision=.7;for(const auto &o:document_->loaded.objects)config.sources.push_back({o.id,true});record("created");generate_water(config,water_test_id_,true);}
      else if(water_test_stage_==2){const auto &w=*selected_water();check(w.cache&&!w.cache->cells.empty(),"Coast button produced no contacts");water_test_stamp_=w.cache->stamp;check(water_test_stamp_==water::input_stamp(*document_,snapshot_),"New cache is already stale");record("coast");choose(0);{auto edit=history_edit(QStringLiteral("移动验证柱体"));snapshot_.values[0].transform.translation_cm.x+=800;send();}}
      else if(water_test_stage_==3){check(water::input_stamp(*document_,snapshot_)!=water_test_stamp_,"Moved collider was not invalidated");choose_water();record("column-moved");water_panel_->findChild<QPushButton *>("WaterRecalculate")->click();check(loading_,"Recalculate UI did not launch worker");}
      else if(water_test_stage_==4){check(water::effective(*document_,snapshot_).front()->cache->stamp!=water_test_stamp_,"Recalculate retained stale geometry");record("recalculated");water_panel_->findChild<QDoubleSpinBox *>("time")->setValue(6.5);check(loading_,"Time field did not submit water state");}
      else if(water_test_stage_==5){check(water::effective(*document_,snapshot_).front()->config.time==6.5&&!water::effective(*document_,snapshot_).front()->cache,"Time edit retained old intersection");record("time");water_panel_->findChild<QPushButton *>("WaterRecalculate")->click();}
      else if(water_test_stage_==6){check(water::effective(*document_,snapshot_).front()->cache!=nullptr,"Time intersection not rebuilt");save_scene_extension(output_/"water-editor.dufex",*document_,snapshot_);record("saved");delete_selection();check(document_->waters.empty(),"Delete did not remove native water");}
      else if(water_test_stage_==7){record("deleted");history_->undo();check(document_->waters.size()==1,"Undo did not restore native water");}
      else if(water_test_stage_==8){record("undo");load(output_/"water-editor.dufex");}
      else if(water_test_stage_==9){check(document_->waters.size()==1&&water::effective(*document_,snapshot_).front()->config.time==6.5&&water::effective(*document_,snapshot_).front()->cache,"Saved water not restored");check(water::input_stamp(*document_,snapshot_)==water::effective(*document_,snapshot_).front()->cache->stamp,"Saved cache validity changed");choose_water();check(!physics_panel_->isVisible()&&ground_panel_->isVisible()&&ground_panel_->isEnabled()&&extension_target()<0,"Native water panel binding is incorrect");record("reopened");{auto edit=history_edit(QStringLiteral("移动水体以验证对齐"));snapshot_.values[selected_].transform.translation_cm.y+=500;send();}}
      else if(water_test_stage_==10){ground_panel_->findChild<QDoubleSpinBox *>("GroundAlignmentOffset")->setValue(25);request_ground();}
      else if(water_test_stage_==11){if(!ground_pending_.empty())return;check(std::abs(state.target_world.at(selected_).point({}).z-.25f)<1e-5,"Water did not align its reference plane with offset");check(water::input_stamp(*document_,snapshot_)!=water::effective(*document_,snapshot_).front()->cache->stamp,"Ground alignment retained a valid coast stamp");record("ground-aligned");water_test_triangles_=state.adapter.triangles;renderer_->camera_view({0,0,0,20000,.1f,.5f});}
      else if(water_test_stage_==12){check(state.adapter.triangles<water_test_triangles_,"Distant camera did not reduce native water tessellation");check(std::abs(state.target_world.at(selected_).point({}).z-.25f)<1e-5,"Water LOD changed ground placement");record("distant-lod");renderer_->camera_view({0,0,0,90,.1f,.5f});}
      else if(water_test_stage_==13){record("near-lod");screen()->grabWindow(winId()).save(QString::fromStdWString((output_/"water-panel.png").wstring()));water_test_triangles_=state.adapter.triangles;water_test_shared_document_=document_.get();water_test_scene_updates_=state.adapter.scene_updates;water_panel_->findChild<QDoubleSpinBox *>("density")->setValue(8);}
      else if(water_test_stage_==14){check(selected_water()->config.density==8&&selected_water()->cache,"Density edit lost recipe/cache");check(state.adapter.triangles>water_test_triangles_&&state.adapter.triangles<=8*water_test_triangles_,"Density render exceeds 8x or did not refine");record("density-8x");screen()->grabWindow(winId()).save(QString::fromStdWString((output_/"water-density-8x.png").wstring()));water_panel_->findChild<QDoubleSpinBox *>("foam_uv_scale")->setValue(.25);}
      else if(water_test_stage_==15){check(selected_water()->config.foam_uv_scale==.25&&selected_water()->cache,"Foam UV edit lost recipe/cache");check(document_.get()==water_test_shared_document_&&state.adapter.scene_updates==water_test_scene_updates_,"Detail edit synchronized entire scene");record("foam-uv-quarter");screen()->grabWindow(winId()).save(QString::fromStdWString((output_/"water-foam-uv.png").wstring()));save_scene_extension(output_/"water-refined.dufex",*document_,snapshot_);load(output_/"water-refined.dufex");}
      else if(water_test_stage_==16){const auto &c=water::effective(*document_,snapshot_).front()->config;check(c.density==8&&c.foam_uv_scale==.25,"Saved density / foam UV not restored");record("refinement-reopened");finish_test(true);water_test_=false;return;}
      ++water_test_stage_;
    }catch(const std::exception &e){finish_test(false,e.what());water_test_=false;}
  }
