"""将 Natural Earth 陆地轮廓转换成离线 Qt 地图使用的墨卡托坐标。"""
import json
import math
from pathlib import Path

root = Path(__file__).resolve().parents[1] / "third_party/natural_earth"
data = json.loads((root / "ne_110m_land.geojson").read_text(encoding="utf-8"))
points, offsets = [], [0]
for feature in data["features"]:
    geometry = feature["geometry"]
    polygons = geometry["coordinates"] if geometry["type"] == "MultiPolygon" else [geometry["coordinates"]]
    for polygon in polygons:
        for ring in polygon:
            for longitude, latitude in ring:
                latitude = math.radians(max(-85.0511287798066, min(85.0511287798066, latitude)))
                x = max(0, min(1, (longitude + 180) / 360))
                y = max(0, min(1, .5 - math.asinh(math.tan(latitude)) / (2 * math.pi)))
                points.append((round(x * 65535), round(y * 65535)))
            offsets.append(len(points))
text = "// Generated by tools/generate_world_map.py. Natural Earth public-domain land outlines.\n"
text += "static constexpr unsigned short land_points[][2]={\n"
text += "".join("{%d,%d},\n" % p for p in points) + "};\n"
text += "static constexpr unsigned land_offsets[]={" + ",".join(map(str, offsets)) + "};\n"
(root / "mercator_land.inl").write_text(text, encoding="utf-8", newline="\n")
print(f"Generated {len(points)} vertices in {len(offsets)-1} rings")
