# 在 Cycles app 目录作用域定义，继承该版本所需的编译选项和 ABI。
add_executable(MatteFogRenderProbe EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/matte_fog_render.cpp" "${DFV_ROOT}/src/cycles/adapter.cpp")
target_include_directories(MatteFogRenderProbe PRIVATE "${DFV_ROOT}/src")
target_link_libraries(MatteFogRenderProbe PRIVATE ${LIB} dfv_scene)
target_compile_definitions(MatteFogRenderProbe PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(MatteFogRenderProbe PRIVATE /utf-8)
add_executable(WaterRenderProbe EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/water_render.cpp" "${DFV_ROOT}/src/cycles/adapter.cpp")
target_include_directories(WaterRenderProbe PRIVATE "${DFV_ROOT}/src")
target_link_libraries(WaterRenderProbe PRIVATE ${LIB} dfv_scene)
target_compile_definitions(WaterRenderProbe PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(WaterRenderProbe PRIVATE /utf-8)
add_executable(CityRenderProbe EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/city_render.cpp" "${DFV_ROOT}/src/cycles/adapter.cpp")
target_include_directories(CityRenderProbe PRIVATE "${DFV_ROOT}/src")
target_link_libraries(CityRenderProbe PRIVATE ${LIB} dfv_scene)
target_compile_definitions(CityRenderProbe PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(CityRenderProbe PRIVATE /utf-8)
add_executable(RenderSchedulerTest "${DFV_ROOT}/tests/render_scheduler.cpp")
target_link_libraries(RenderSchedulerTest PRIVATE ${LIB})
target_compile_options(RenderSchedulerTest PRIVATE /utf-8)
add_test(NAME render_scheduler COMMAND RenderSchedulerTest)
add_executable(CyclesViewportBench "${DFV_ROOT}/src/bench/main.cpp"
  "${DFV_ROOT}/src/bench/fixtures.cpp"
  "${DFV_ROOT}/src/cycles/adapter.cpp"
  "${DFV_ROOT}/src/viewport/window.cpp"
  "${DFV_ROOT}/src/viewport/display.cpp" "${DFV_ROOT}/src/viewport/overlay.cpp")
target_include_directories(CyclesViewportBench PRIVATE "${DFV_ROOT}/src")
target_link_libraries(CyclesViewportBench PRIVATE ${LIB} dfv_scene bf::dependencies::epoxy
  opengl32 gdi32 user32 dwmapi psapi winmm)
target_compile_definitions(CyclesViewportBench PRIVATE
  NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(CyclesViewportBench PRIVATE /utf-8)
install(TARGETS CyclesViewportBench RUNTIME DESTINATION "${CMAKE_INSTALL_PREFIX}")
install(FILES "${DFV_LIB_DIR}/epoxy/bin/epoxy-0.dll" DESTINATION "${CMAKE_INSTALL_PREFIX}")

find_package(Qt6 6.10 REQUIRED COMPONENTS Widgets Test HINTS "${DFV_QT_ROOT}/lib/cmake/Qt6")
add_executable(WindowPlacementTest "${DFV_ROOT}/tests/window_placement.cpp" "${DFV_ROOT}/src/viewport/window.cpp")
target_include_directories(WindowPlacementTest PRIVATE "${DFV_ROOT}/src" "${DFV_ROOT}/third_party")
target_link_libraries(WindowPlacementTest PRIVATE Qt6::Widgets opengl32 gdi32 user32 dwmapi psapi winmm)
target_compile_definitions(WindowPlacementTest PRIVATE NOMINMAX QT_NO_KEYWORDS)
target_compile_options(WindowPlacementTest PRIVATE /utf-8)
add_test(NAME window_placement COMMAND WindowPlacementTest)
# Derive deployment tools from the Qt actually selected (also supports Qt6_DIR).
get_target_property(_dfv_qmake Qt6::qmake IMPORTED_LOCATION)
get_filename_component(_dfv_qt_bin "${_dfv_qmake}" DIRECTORY)
get_filename_component(DFV_QT_ROOT "${_dfv_qt_bin}" DIRECTORY)
set(DFV_QT_ROOT "${DFV_QT_ROOT}" CACHE PATH "Selected Qt installation" FORCE)
add_library(dfv_history STATIC "${DFV_ROOT}/src/editor/edit_history.cpp" "${DFV_ROOT}/src/editor/recovery.cpp")
target_link_libraries(dfv_history PUBLIC dfv_scene Qt6::Widgets)
target_compile_options(dfv_history PRIVATE /utf-8)
target_compile_definitions(dfv_history PRIVATE QT_NO_KEYWORDS NOMINMAX)
add_executable(EditHistoryTest "${DFV_ROOT}/tests/edit_history.cpp" "${DFV_ROOT}/src/editor/material_panel.cpp")
target_link_libraries(EditHistoryTest PRIVATE dfv_history Qt6::Test)
target_compile_options(EditHistoryTest PRIVATE /utf-8)
target_compile_definitions(EditHistoryTest PRIVATE QT_NO_KEYWORDS NOMINMAX)
add_test(NAME edit_history COMMAND EditHistoryTest)
set_tests_properties(edit_history PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${DFV_QT_ROOT}/bin")
add_library(dfv_content STATIC "${DFV_ROOT}/src/editor/content_browser.cpp" "${DFV_ROOT}/src/editor/content_catalog.cpp" "${DFV_ROOT}/src/editor/ui_scale.cpp")
target_sources(dfv_content PRIVATE "${DFV_ROOT}/src/editor/viewport_settings.cpp" "${DFV_ROOT}/src/editor/application_settings.cpp" "${DFV_ROOT}/src/editor/content_locator.cpp")
target_include_directories(dfv_content PUBLIC "${DFV_ROOT}/src" "${DFV_ROOT}/third_party")
target_link_libraries(dfv_content PUBLIC Qt6::Widgets dfv_scene)
target_compile_options(dfv_content PRIVATE /utf-8)
target_compile_definitions(dfv_content PRIVATE QT_NO_KEYWORDS NOMINMAX)
qt_add_executable(DazFastViewer WIN32 "${DFV_ROOT}/src/editor/main.cpp"
  "${DFV_ROOT}/src/editor/chrome.cpp"
  "${DFV_ROOT}/src/editor/extension_panel.cpp"
  "${DFV_ROOT}/src/editor/material_panel.cpp"
  "${DFV_ROOT}/src/editor/powerpose_panel.cpp"
  "${DFV_ROOT}/src/editor/project.cpp" "${DFV_ROOT}/src/editor/parameters.cpp"
  "${DFV_ROOT}/src/editor/renderer.cpp" "${DFV_ROOT}/src/bench/fixtures.cpp"
  "${DFV_ROOT}/src/cycles/adapter.cpp" "${DFV_ROOT}/src/viewport/window.cpp"
  "${DFV_ROOT}/src/viewport/display.cpp" "${DFV_ROOT}/src/viewport/overlay.cpp")
target_include_directories(DazFastViewer PRIVATE "${DFV_ROOT}/src")
target_sources(DazFastViewer PRIVATE "${DFV_ROOT}/src/city/panel.cpp")
target_sources(DazFastViewer PRIVATE "${DFV_ROOT}/src/water/panel.cpp")
target_sources(DazFastViewer PRIVATE "${DFV_ROOT}/src/cloud/panel.cpp")
add_executable(CloudPanelTest "${DFV_ROOT}/tests/cloud_panel.cpp" "${DFV_ROOT}/src/cloud/panel.cpp")
target_link_libraries(CloudPanelTest PRIVATE dfv_scene Qt6::Widgets Qt6::Test)
target_compile_options(CloudPanelTest PRIVATE /utf-8)
add_test(NAME cloud_panel COMMAND CloudPanelTest)
add_executable(CloudRenderProbe EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/cloud_render.cpp" "${DFV_ROOT}/src/cycles/adapter.cpp")
target_include_directories(CloudRenderProbe PRIVATE "${DFV_ROOT}/src")
target_link_libraries(CloudRenderProbe PRIVATE ${LIB} dfv_scene)
target_compile_definitions(CloudRenderProbe PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(CloudRenderProbe PRIVATE /utf-8)
target_link_libraries(DazFastViewer PRIVATE ${LIB} dfv_scene dfv_content Qt6::Widgets bf::dependencies::epoxy opengl32 gdi32 user32 dwmapi psapi winmm)
target_link_libraries(DazFastViewer PRIVATE dfv_history)
target_compile_definitions(DazFastViewer PRIVATE QT_NO_KEYWORDS NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(DazFastViewer PRIVATE /utf-8)
set_target_properties(DazFastViewer PROPERTIES
  VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:DazFastViewer>")
if(DFV_STAGE_EDITOR_RUNTIME)
  add_custom_command(TARGET DazFastViewer POST_BUILD
    COMMAND "${CMAKE_COMMAND}" -E env PYTHONUTF8=1
      "${Python3_EXECUTABLE}" "${DFV_ROOT}/tools/stage_runtime.py"
      --build-dir "${CMAKE_BINARY_DIR}" --configuration "$<CONFIG>"
      --editor-only --output "$<TARGET_FILE_DIR:DazFastViewer>"
    COMMENT "Deploying DazFastViewer dependencies for Visual Studio launch"
    VERBATIM)
endif()
add_executable(RendererQualityTest EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/renderer_quality.cpp"
  "${DFV_ROOT}/src/editor/renderer.cpp" "${DFV_ROOT}/src/cycles/adapter.cpp" "${DFV_ROOT}/src/bench/fixtures.cpp"
  "${DFV_ROOT}/src/viewport/window.cpp" "${DFV_ROOT}/src/viewport/display.cpp" "${DFV_ROOT}/src/viewport/overlay.cpp")
target_include_directories(RendererQualityTest PRIVATE "${DFV_ROOT}/src")
target_link_libraries(RendererQualityTest PRIVATE ${LIB} dfv_scene Qt6::Widgets bf::dependencies::epoxy opengl32 gdi32 user32 dwmapi psapi winmm)
target_compile_definitions(RendererQualityTest PRIVATE QT_NO_KEYWORDS NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(RendererQualityTest PRIVATE /utf-8)
add_executable(RendererMaterialsTest EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/renderer_materials.cpp"
  "${DFV_ROOT}/src/editor/renderer.cpp" "${DFV_ROOT}/src/cycles/adapter.cpp" "${DFV_ROOT}/src/bench/fixtures.cpp"
  "${DFV_ROOT}/src/viewport/window.cpp" "${DFV_ROOT}/src/viewport/display.cpp" "${DFV_ROOT}/src/viewport/overlay.cpp")
target_include_directories(RendererMaterialsTest PRIVATE "${DFV_ROOT}/src")
target_link_libraries(RendererMaterialsTest PRIVATE ${LIB} dfv_scene Qt6::Widgets bf::dependencies::epoxy opengl32 gdi32 user32 dwmapi psapi winmm)
target_compile_definitions(RendererMaterialsTest PRIVATE QT_NO_KEYWORDS NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(RendererMaterialsTest PRIVATE /utf-8)
add_executable(RendererRecoveryTest EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/renderer_recovery.cpp"
  "${DFV_ROOT}/src/editor/renderer.cpp" "${DFV_ROOT}/src/cycles/adapter.cpp" "${DFV_ROOT}/src/bench/fixtures.cpp"
  "${DFV_ROOT}/src/viewport/window.cpp" "${DFV_ROOT}/src/viewport/display.cpp" "${DFV_ROOT}/src/viewport/overlay.cpp")
target_include_directories(RendererRecoveryTest PRIVATE "${DFV_ROOT}/src")
target_link_libraries(RendererRecoveryTest PRIVATE ${LIB} dfv_scene Qt6::Widgets bf::dependencies::epoxy opengl32 gdi32 user32 dwmapi psapi winmm)
target_compile_definitions(RendererRecoveryTest PRIVATE DFV_GL_RECOVERY_TEST QT_NO_KEYWORDS NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(RendererRecoveryTest PRIVATE /utf-8)
add_executable(RendererInteractionTest EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/renderer_interaction.cpp"
  "${DFV_ROOT}/src/editor/renderer.cpp" "${DFV_ROOT}/src/cycles/adapter.cpp" "${DFV_ROOT}/src/bench/fixtures.cpp"
  "${DFV_ROOT}/src/viewport/window.cpp" "${DFV_ROOT}/src/viewport/display.cpp" "${DFV_ROOT}/src/viewport/overlay.cpp")
target_include_directories(RendererInteractionTest PRIVATE "${DFV_ROOT}/src")
target_link_libraries(RendererInteractionTest PRIVATE ${LIB} dfv_scene Qt6::Widgets bf::dependencies::epoxy opengl32 gdi32 user32 dwmapi psapi winmm)
target_compile_definitions(RendererInteractionTest PRIVATE DFV_RENDER_INTERACTION_TEST QT_NO_KEYWORDS NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(RendererInteractionTest PRIVATE /utf-8)
add_executable(RendererPhysicsTest EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/renderer_physics.cpp"
  "${DFV_ROOT}/src/editor/renderer.cpp" "${DFV_ROOT}/src/cycles/adapter.cpp" "${DFV_ROOT}/src/bench/fixtures.cpp"
  "${DFV_ROOT}/src/viewport/window.cpp" "${DFV_ROOT}/src/viewport/display.cpp" "${DFV_ROOT}/src/viewport/overlay.cpp")
target_include_directories(RendererPhysicsTest PRIVATE "${DFV_ROOT}/src")
target_link_libraries(RendererPhysicsTest PRIVATE ${LIB} dfv_scene Qt6::Widgets bf::dependencies::epoxy opengl32 gdi32 user32 dwmapi psapi winmm)
target_compile_definitions(RendererPhysicsTest PRIVATE DFV_PHYSICS_TEST QT_NO_KEYWORDS NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(RendererPhysicsTest PRIVATE /utf-8)
add_executable(ProjectSettingsTest "${DFV_ROOT}/tests/project_settings.cpp" "${DFV_ROOT}/src/editor/project.cpp" "${DFV_ROOT}/src/editor/application_settings.cpp")
target_include_directories(ProjectSettingsTest PRIVATE "${DFV_ROOT}/src" "${DFV_ROOT}/third_party")
target_link_libraries(ProjectSettingsTest PRIVATE Qt6::Widgets)
target_compile_options(ProjectSettingsTest PRIVATE /utf-8)
add_test(NAME project_settings COMMAND ProjectSettingsTest)
set_tests_properties(project_settings PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${DFV_QT_ROOT}/bin")
add_executable(ParameterControlsTest "${DFV_ROOT}/tests/parameter_controls.cpp" "${DFV_ROOT}/src/editor/parameters.cpp")
target_sources(ParameterControlsTest PRIVATE "${DFV_ROOT}/src/editor/extension_panel.cpp")
target_include_directories(ParameterControlsTest PRIVATE "${DFV_ROOT}/src")
target_link_libraries(ParameterControlsTest PRIVATE dfv_scene Qt6::Widgets Qt6::Test)
target_compile_options(ParameterControlsTest PRIVATE /utf-8)
add_test(NAME parameter_controls COMMAND ParameterControlsTest)
add_executable(WaterPanelTest "${DFV_ROOT}/tests/water_panel.cpp" "${DFV_ROOT}/src/water/panel.cpp")
target_link_libraries(WaterPanelTest PRIVATE dfv_scene Qt6::Widgets Qt6::Test)
target_compile_options(WaterPanelTest PRIVATE /utf-8)
add_test(NAME water_panel COMMAND WaterPanelTest)
set_tests_properties(water_panel PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${DFV_QT_ROOT}/bin")
add_executable(MaterialsTest "${DFV_ROOT}/tests/materials.cpp" "${DFV_ROOT}/src/editor/material_panel.cpp")
target_link_libraries(MaterialsTest PRIVATE dfv_scene dfv_content Qt6::Widgets Qt6::Test)
target_compile_options(MaterialsTest PRIVATE /utf-8)
target_compile_definitions(MaterialsTest PRIVATE NOMINMAX QT_NO_KEYWORDS)
add_test(NAME materials COMMAND MaterialsTest)
set_tests_properties(materials PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${DFV_QT_ROOT}/bin")
add_executable(PowerPosePanelTest "${DFV_ROOT}/tests/powerpose_panel.cpp" "${DFV_ROOT}/src/editor/powerpose_panel.cpp")
target_link_libraries(PowerPosePanelTest PRIVATE dfv_scene Qt6::Widgets Qt6::Test)
target_compile_options(PowerPosePanelTest PRIVATE /utf-8)
target_compile_definitions(PowerPosePanelTest PRIVATE NOMINMAX QT_NO_KEYWORDS)
add_test(NAME powerpose_panel COMMAND PowerPosePanelTest)
add_executable(EditorChromeTest "${DFV_ROOT}/tests/editor_chrome.cpp" "${DFV_ROOT}/src/editor/chrome.cpp")
target_link_libraries(EditorChromeTest PRIVATE dfv_scene Qt6::Widgets Qt6::Test dwmapi)
target_compile_options(EditorChromeTest PRIVATE /utf-8)
target_compile_definitions(EditorChromeTest PRIVATE NOMINMAX QT_NO_KEYWORDS)
add_test(NAME editor_chrome COMMAND EditorChromeTest)
set_tests_properties(editor_chrome PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${DFV_QT_ROOT}/bin")
set_tests_properties(powerpose_panel PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${DFV_QT_ROOT}/bin")
set_tests_properties(parameter_controls PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${DFV_QT_ROOT}/bin")
add_executable(ContentBrowserTest "${DFV_ROOT}/tests/content_browser.cpp")
target_link_libraries(ContentBrowserTest PRIVATE dfv_content Qt6::Test)
target_compile_options(ContentBrowserTest PRIVATE /utf-8)
add_test(NAME content_browser COMMAND ContentBrowserTest)
add_executable(UiScaleTest "${DFV_ROOT}/tests/ui_scale.cpp" "${DFV_ROOT}/src/editor/chrome.cpp")
target_link_libraries(UiScaleTest PRIVATE dfv_content dfv_scene Qt6::Test dwmapi)
target_compile_options(UiScaleTest PRIVATE /utf-8)
target_compile_definitions(UiScaleTest PRIVATE NOMINMAX QT_NO_KEYWORDS)
add_test(NAME ui_scale COMMAND UiScaleTest)
set_tests_properties(ui_scale PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${DFV_QT_ROOT}/bin")
set_tests_properties(content_browser PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${DFV_QT_ROOT}/bin")
add_executable(ViewportOverlayTest EXCLUDE_FROM_ALL "${DFV_ROOT}/tests/viewport_overlay.cpp" "${DFV_ROOT}/src/viewport/window.cpp" "${DFV_ROOT}/src/viewport/overlay.cpp")
target_sources(ViewportOverlayTest PRIVATE "${DFV_ROOT}/src/viewport/display.cpp")
target_include_directories(ViewportOverlayTest PRIVATE "${DFV_ROOT}/src")
target_link_libraries(ViewportOverlayTest PRIVATE ${LIB} dfv_scene Qt6::Gui bf::dependencies::epoxy opengl32 gdi32 user32 dwmapi winmm)
target_compile_options(ViewportOverlayTest PRIVATE /utf-8)
target_compile_definitions(ViewportOverlayTest PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
