# 仅定义本基准实际采用的依赖；不引入 Blender 核心库。
function(dfv_dependency alias includes)
  string(REPLACE "::" "_" name "${alias}")
  add_library(${name} INTERFACE)
  add_library(${alias} ALIAS ${name})
  if(includes)
    target_include_directories(${name} SYSTEM INTERFACE ${includes})
  endif()
  if(ARGN)
    target_link_libraries(${name} INTERFACE ${ARGN})
  endif()
endfunction()

add_library(bf::dependencies::openimageio ALIAS OpenImageIO::OpenImageIO)
add_library(bf::dependencies::openexr ALIAS OpenEXR::OpenEXR)
add_library(bf::dependencies::opencolorio ALIAS OpenColorIO::OpenColorIO)
find_package(fmt REQUIRED CONFIG)
dfv_dependency(bf::dependencies::optional::tbb "${TBB_INCLUDE_DIRS}" ${TBB_LIBRARIES})
target_compile_definitions(bf_dependencies_optional_tbb INTERFACE WITH_TBB)
dfv_dependency(bf::dependencies::zlib "${ZLIB_INCLUDE_DIRS}" ${ZLIB_LIBRARIES})
dfv_dependency(bf::dependencies::zstd "${ZSTD_INCLUDE_DIRS}" ${ZSTD_LIBRARIES})
dfv_dependency(bf::dependencies::optional::pugixml "${PUGIXML_INCLUDE_DIR}" ${PUGIXML_LIBRARIES})
# Windows 上 Cycles 使用 std::thread；不链接 pthreads 实现。
dfv_dependency(bf::dependencies::pthreads "")
dfv_dependency(bf::dependencies::epoxy "${DFV_LIB_DIR}/epoxy/include" "${DFV_LIB_DIR}/epoxy/lib/epoxy.lib")
foreach(dep embree openimagedenoise openpgl opensubdiv openvdb nanovdb osl python sdl usd)
  dfv_dependency(bf::dependencies::optional::${dep} "")
endforeach()
