# 固定 CPU 引擎版本；正式构建与独立探针复用本机已验证源码。
set(DFV_JOLT_SOURCE "${DFV_ROOT}/.research/JoltPhysics-v5.6.0" CACHE PATH "Jolt Physics 源码")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${DFV_ROOT}/tools/ensure_jolt.py" "${DFV_JOLT_SOURCE}" COMMAND_ERROR_IS_FATAL ANY)
foreach(flag JPH_USE_DX12 JPH_USE_VK JPH_USE_MTL JPH_USE_CPU_COMPUTE JPH_BUILD_SHARED_LIBS
    INTERPROCEDURAL_OPTIMIZATION USE_STATIC_MSVC_RUNTIME_LIBRARY OVERRIDE_CXX_FLAGS ENABLE_ALL_WARNINGS
    GENERATE_DEBUG_SYMBOLS ENABLE_INSTALL DEBUG_RENDERER_IN_DEBUG_AND_RELEASE PROFILER_IN_DEBUG_AND_RELEASE
    FLOATING_POINT_EXCEPTIONS_ENABLED USE_AVX512)
  set(${flag} OFF CACHE BOOL "DFV CPU 物理" FORCE)
endforeach()
add_subdirectory("${DFV_JOLT_SOURCE}/Build" jolt)
